### PR TITLE
Add clone implementation for Storage

### PR DESCRIPTION
**Pull request by distransient**
## Checklist

* [x] **(not applicable)** I've added tests for all code changes and additions (where applicable)
* [x] **(not necessary)** I've added a demonstration of the new feature to one or more examples
* [x] **(not necessary)** I've updated the book to reflect my changes
* [x] **(trait impl will appear in rustdoc)** Usage of new public items is shown in the API docs

## API changes

This allows users to clone their `ReadStorage` and `WriteStorage` ***fetches*** by adding `Clone` for `Storage<'a, T, D: Clone>`.

### CODE REVIEW

**Comment by Rua** [comment]
I'd be interested in seeing this merged.

**Comment by azriel91** [comment]
By the way, builds won't succeed right now due to https://github.com/rust-lang/rust/issues/67743 (we don't allow failures on nightly right now)

**Comment by Rua** [comment]
I notice this never got added to the changelog. What version was this added in?

**Comment by ebkalderon** [comment]
@Rua The tag information for the Bors merge commit apparently indicates it existed since 0.16.0.

**Pull request merged**
