### PR TITLE
Update shred version

### PR DESCRIPTION
**Pull request by allphyr**
Note : it bumps minimal Rust version to 1.38

### CODE REVIEW

**Comment by azriel91** [comment]
By the way, could you remove the `"nightly"` feature (and references to it) altogether? It's no longer used (yay!). I think is is an exhaustive list:

* Cargo.toml
* `src/lib.rs`
* `scripts/build-netlify.sh`
* `docs/tutorials/src/14_troubleshooting.md` (would need to fix the text)

**Comment by allphyr** [comment]
Those two commits should fix the CI failures

**Comment by azriel91** [comment]
bors try

**Comment by azriel91** [comment]
ah, `tynm` is me. Shall swap that for `unimplemented!()`.

**Comment by azriel91** [comment]
ah, you're fast :rocket:

bors r+

**Pull request merged**
