### PR TITLE
Remove `rudy` and `common`

### PR DESCRIPTION
**Pull request by torkleyy**
This change is [Reviewable](https://reviewable.io/reviews/slide-rs/specs/542)

### CODE REVIEW

**Comment by torkleyy** [comment]
Goals:

* Remove unnecessary dependencies
* Remove discouraged patterns (`Future` merging)
* Balance Travis build channels for faster CI

Part of: #532 

**This is a breaking change**

This will be documented in the CHANGELOG, but I want to stop doing that for every single PR; I'll do that together with the version bumps for now; automate if I have the time.

bors r+

**Comment by torkleyy** [comment]
Retrying on top of #543 

bors r+

**Comment by torkleyy** [comment]
16 minutes :tada:

**Comment by ishitatsuyuki** [comment]
I think you may want to add this to the changelog!

**Comment by torkleyy** [comment]
Oops, forgot that! https://github.com/slide-rs/specs/pull/616

**Pull request merged**
